name: CI - Test Déploiement

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout du code
        uses: actions/checkout@v4

      - name: Donner les droits d'exécution aux scripts
        run: chmod +x test_deploy.sh

      - name: Lancer les tests de déploiement
        run: ./test_deploy.sh
